name: etherstash
description: An efficient and concise note-taking tool with self-hosted cloud sync support

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.1+5

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_staggered_grid_view: ^0.7.0
  flutter_staggered_animations: ^1.1.1
  hive: ^2.2.3         # Hive 的核心库
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  http: ^1.2.2
  tray_manager: ^0.5.0
  window_manager: ^0.4.0
  screen_retriever: ^0.2.0
  desktop_multi_window: ^0.2.1

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  msix: ^3.16.7
 
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
